### ISSUE TITLE
import patterns 出错

### ISSUE THREAD

**Issue by pompeybrain** [phodal/growth-in-action-django#14]
我使用了django 1.10 版本，urls.patterns 好像被移除了，然后就报错如下
ImportError: cannot import name 'patterns'
官网上有这么一句话 urlpatterns should be a plain list of django.conf.urls.url() instances instead
我刚接触django，不知道怎么改这方面的代码

**Comment by phodal** [comment]
@pompeybrain 这种问题可以自己先Google一下啦。。
