### ISSUE TITLE
django版本更新以后好多地方不一样了，对于我这种新手有点坑。

### ISSUE THREAD

**Issue by ocean69** [phodal/growth-in-action-django#15]
我在windows 10 x64上用python2.7.11现在pip默认安装是django 1.10.2，里面有一些操作跟教程里的已经不相符了。例如MIDDLEWARE_CLASS已经不是默认开启了，不修改一下配置直接访问admin会出异常，还有urlpatterns设置的代码也有一些变化。

**Comment by phodal** [comment]
@ocean69 我最近在编写Growth 的纸质版，应该在这个月会对这个项目的代码进行更新的。

**Comment by ocean69** [comment]
@phodal 哦 哦 谢谢。
