### ISSUE TITLE
有几个纯新手问题

### ISSUE THREAD

**Issue by Leonard1379** [phodal/growth-in-action-django#17]
1.请问，「创建View」章节，templates文件夹应该放在哪个路径下？
2.「测试」章节，测试代码写在哪里？测试没通过应该如何根据提示来定位修复呢？

**Comment by phodal** [comment]
代码在：https://github.com/phodal/growth-in-action-code，你应该可以看到

**Comment by Leonard1379** [comment]
Google了一下，发现有些是Django 1.10的坑，对新手来说有点难解决……感觉和另一个已经关闭的Issue说的是同一个问题

**Comment by phodal** [comment]
@Leonard1379 欢迎来 PR
