### ISSUE TITLE
Growth实战篇PDF第18页缺部分步骤

### ISSUE THREAD

**Issue by Anywmel** [phodal/growth-in-action-django#18]
PDF版18页缺少
```
将blogpost这个APP添加到setting.py中的INSTALLED_APPS字段中
```
以及数据库迁移部分

**Comment by guyunguyun** [comment]
对的，在“进入后台，我们就可以看到BLOGPOST的一栏里...”之前添加：

修改配置文件 _blog/blog/settings.py_
`INSTALLED_APPS = [
    'blogpost.apps.BlogpostConfig',
    'django.contrib.admin',
    ...
]`

**Comment by phodal** [comment]
@guyunguyun 来个 PR？

**Comment by guyunguyun** [comment]
@phodal 发了
