### ISSUE TITLE
创建blogpostmodel时遇到问题

### ISSUE THREAD

**Issue by Deeer** [phodal/growth-in-action-django#3]
你好，我在按照步骤做的时候出现了一个问题
具体文件目录
![wechat_1464018169](https://cloud.githubusercontent.com/assets/8898286/15476255/a4a4c854-2140-11e6-939e-b9bfb78faf0b.jpeg)

然后按步骤创建了model

![wechat_1464018237](https://cloud.githubusercontent.com/assets/8898286/15476308/e3f92c70-2140-11e6-89eb-c4cb5433f0a9.jpeg)

但是执行python manage.py runserver时，没有出现BLOGPOST部分，请问问题出在哪里？

**Comment by phodal** [comment]
没有migrate？

**Comment by Deeer** [comment]
已经迁移好了
