### ISSUE TITLE
chapter4创建`sitemap.xml`模版问题

### ISSUE THREAD

**Issue by OswaldoBornemann** [phodal/growth-in-action-django#4]
我想问下 具体的这个sitemap.xml应该放在哪个文件夹下面？

然后要怎么才能够让它产生作用？

我试了三四个小时都不知道。。

**Comment by phodal** [comment]
sitemap.xml 要放在 templates目录下

**Comment by OswaldoBornemann** [comment]
那我觉得可能在urls.py里面应该要这样写 
    `url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps, 'template_name': 'sitemap.xml'}, name='django.contrib.sitemaps.views.sitemap'),`

就是要指明`template_name`吧？

**Comment by phodal** [comment]
@tsungruihon 最近比较忙，忘回了。它的name决定了view来自于`django.contrib.sitemaps.views.sitemap`，在这其中指定了 sitemap.xml 的位置。

``` python
def sitemap(request, sitemaps, section=None,
            template_name='sitemap.xml', content_type='application/xml'):
```

不过，我应该在内容里面详细说明一下。 

Thanks
